# Generated by Django 5.2 on 2025-05-14 13:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BangunanPogung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(blank=True, max_length=254, null=True)),
                ("jenis", models.CharField(blank=True, max_length=254, null=True)),
                ("pemilik", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
