# Generated by Django 5.2 on 2025-05-18 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batasdesa", "0001_initial"),
        ("peta", "0002_remove_superhero_lat_remove_superhero_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bangunanpogung",
            name="pemilik",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="peta.superhero",
            ),
        ),
    ]
